"""Load a frozen benchmark suite (generated by experiments/suites/generate_suite.py) and rebuild each classifier into an SDD under a chosen vtree.

Usage:
    from rgr.suite import load_suite, build_classifier
    suite = load_suite("standard")
    for entry in suite["classifiers"]:
        mgr, sdd = build_classifier(entry, vtree_type="right")
"""
import json, os
from .sdd_utils import build

_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "data", "suites")

def load_suite(name="standard", path=None):
    p = path or os.path.join(_DIR, f"{name}.json")
    with open(p) as fh:
        return json.load(fh)

def build_classifier(entry, vtree_type="right"):
    """Rebuild one suite entry into (mgr, sdd) under the given vtree."""
    nvars = entry["nvars"]
    mgr, _ = build(nvars, vtree_type=vtree_type)
    f = mgr.true()
    for clause in entry["clauses"]:
        c = mgr.false()
        for lit in clause:
            c = c | mgr.literal(lit)
        f = f & c
    return mgr, f
